package bolt

//fmt.Println()
//link, err := storage.GetLink("1")
//fmt.Println(link, err)
//err = storage.SetLink("1", "mylink")
//fmt.Println(err)
//link, err = storage.GetLink("1")
//fmt.Println(link, err)
//pay, err := storage.Get("1")
//fmt.Println(pay, err)
//err = storage.Set("1", payment.Payment{Price: 100, Status: "New", User: user.User{Name: "Name", Email: "test@mail.ru"}})
//fmt.Println(err)
//pay, err = storage.Get("1")
//fmt.Println(pay, err)
//err = storage.UpdateStatus("1", "Payed")
//fmt.Println(err)
//pay, err = storage.Get("1")
//fmt.Println(pay, err)
